[network.ws.server]
	# 服务器监听地址
	addr = ":3553"
	# 客户端连接路径
	path = "/"
	# 服务器最大连接数
	maxConnNum = 5000
	# 秘钥文件
	keyFile = ""
	# 证书文件
	certFile = ""
	# 跨域检测，空数组时不允许任何连接升级成websocket，未设置此参数时允许所有的链接升级成websocket
	origins = ["*"]
	# 握手超时时间，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为10s
	handshakeTimeout = "10s"
	# 心跳检测间隔时间。设置为0则不启用心跳检测，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为10s
	heartbeatInterval = "10s"
	# 心跳机制，默认为resp响应式心跳。可选：resp 响应式心跳 | tick 定时主推心跳
	heartbeatMechanism = "resp"
	# 授权超时时间，（在客户端建立连接后，如果在授权超时时间内未进行绑定用户操作，则被认定为未授权连接，服务器会强制断开连接）支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为0s，不进行授权检测
	authorizeTimeout = "0s"