[cluster.mesh]
	# 实例ID，集群中唯一。不填写默认自动生成唯一的实例ID
	id = ""
	# 实例名称
	name = "{{.Name}}"
	# 是否将内部通信地址暴露到公网。默认为false
	expose = false
	# 编解码器。可选：json | proto。默认为proto
	codec = "{{.Codec}}"
	# 实例元数据
	[cluster.mesh.metadata]
		# 键值对，且均为字符串类型。由于注册中心的元数据参数限制，建议将键值对的数量控制在20个以内，键的字符长度控制在127个字符内，值得字符长度控制在512个字符内。
		key = "value"