package packages

var Packages = []string{
	"github.com/dobyte/due",
	"github.com/dobyte/due/cache/memcache",
	"github.com/dobyte/due/cache/redis",
	"github.com/dobyte/due/component/http",
	"github.com/dobyte/due/config/consul",
	"github.com/dobyte/due/config/etcd",
	"github.com/dobyte/due/config/nacos",
	"github.com/dobyte/due/crypto/ecc",
	"github.com/dobyte/due/crypto/rsa",
	"github.com/dobyte/due/eventbus/kafka",
	"github.com/dobyte/due/eventbus/nats",
	"github.com/dobyte/due/eventbus/redis",
	"github.com/dobyte/due/locate/redis",
	"github.com/dobyte/due/lock/memcache",
	"github.com/dobyte/due/lock/redis",
	"github.com/dobyte/due/log/aliyun",
	"github.com/dobyte/due/log/tencent",
	"github.com/dobyte/due/network/kcp",
	"github.com/dobyte/due/network/tcp",
	"github.com/dobyte/due/network/ws",
	"github.com/dobyte/due/registry/consul",
	"github.com/dobyte/due/registry/etcd",
	"github.com/dobyte/due/registry/nacos",
	"github.com/dobyte/due/transport/grpc",
	"github.com/dobyte/due/transport/rpcx",
}
